### ISSUE TITLE
Run migrations against protected databases

### ISSUE THREAD

**Issue by ankit-agrawal11** [causecode/grails-mongeez#3]
When the database is protected with username and password, the migrations fail to run. Find the cause and fix it.

**Comment by ankit-agrawal11** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Grails Mongeez - Test grails-mongeez migration with authentication enabled #3](https://trello.com/c/5oz5mA9a/571-grails-mongeez-test-grails-mongeez-migration-with-authentication-enabled-3)

**Comment by hardikmodha** [comment]
Fixed in https://github.com/causecode/grails-mongeez/pull/4
